### ISSUE TITLE
Pickaxes don't work on stone, Ores and Decorative Blocks in 1.18.2

### ISSUE THREAD

**Issue by DerEchteLappen** [Slomaxonical-907/Architects-Palette-Fabric#10]
I Can't Say what is causing the issue but Vanilla Pickaxes even Modded ones don't work when used on stone, Ores and Decorative blocks.
Pickaxes take about 7 seconds to break and don't drop Items from the Broken Block or the result of breaking the block, like Raw Ore.

I noticed the issue when I tried making a Modpack, after some Trial and Error Removing some mods and re-adding them It came out the issue came from Architect's Palette Fabric.

Hopefully you can fix this issue soon because I love this Mod!
Stay healthy and don't overwhelm yourself by fixing the issue.

**Comment by Slomaxonical-907** [comment]
this should be fixed in latest release (once approved)
