### ISSUE TITLE
[BUG] Pickaxes are non-functional due to missing references in the minecraft:mineable/pickaxe tag

### ISSUE THREAD

**Issue by Gemini04126** [Slomaxonical-907/Architects-Palette-Fabric#11]
These are the problematic entries:
architects_palette:heliodor_rod
architects_palette:ekanite_rod
architects_palette:monazite_rod
I'd assume these are just unimplemented items, but I'm not sure, as I haven't played around with the mod enough.

**Comment by Slomaxonical-907** [comment]
are u on the latest version? 
I'm pretty sure i fixed this

**Comment by Arthree** [comment]
Just tested this. Pickaxes work fine (???). Those 3 items don't exist and they throw exceptions during loading:

`[29/03/2022 16:30:48 p.m.] [Render thread/ERROR] Couldn't parse loot table architects_palette:blocks/monazite_rod`
etc.

**Comment by Gemini04126** [comment]
It says that it was last updated 14 days ago, but I downloaded it yesterday. Does that count as the latest version?
The version number is 1.7. EDIT: Wait, nevermind, Curseforge has a 1.7-fix JAR for it. Oops?
Yeah, it works now. I'll close this. Should've checked both before commenting.
