### ISSUE TITLE
Potential Crashing w/Fabric API Update

### ISSUE THREAD

**Issue by Rage-GitHub** [Slomaxonical-907/Architects-Palette-Fabric#16]
Some issue with the new Fabric API update and the mod may be causing issues after loading into a newly created world.

Fabric 0.14.6
MC 1.18.2

**Crash Log**
https://gist.github.com/Rage-GitHub/d465504abf07743665c9ac1ede489e88
**Latest Log**
https://gist.github.com/Rage-GitHub/77ff0d8db69e9cfc2da1fb5389dc8e70

**Comment by Slomaxonical-907** [comment]
it is not a fapi version issue, but tanks for reporting! it should be fixed and uploaded to cf, ill keep this open for now cause i actually didnt test still XD (feel free to close if this is no longer an issue)
