### ISSUE TITLE
Nether Brass stairs and slabs glow

### ISSUE THREAD

**Issue by Eldog02** [Slomaxonical-907/Architects-Palette-Fabric#17]
Seems pretty self-explanatory.

Tested with and without shaders, all non-full blocks (stairs, slabs, walls) of Nether Brass glow, but not full blocks. Not sure what is intended behavior here to be honest. If this _is_ intended, unifying the behavior between full blocks and partial blocks would be nice.

**Comment by Slomaxonical-907** [comment]
definetly not intended, fix released soon along with the other sunmetal issue, thx for reporting <3
