### ISSUE TITLE
Crashing with Hydrogen

### ISSUE THREAD

**Issue by Heamaci** [Slomaxonical-907/Architects-Palette-Fabric#2]
I removed every single mod until i could find the one causing the problem and hydrogen seems to be incompatible. It will straight up not launch without error message or anything when the mod is installed.

**Comment by Slomaxonical-907** [comment]
seems like it will be fixed in Hydrogen 0.3
but I will try to fix it on my side asap.

**Comment by Slomaxonical-907** [comment]
fixed in next version

**Comment by Slomaxonical-907** [comment]
seems like this is back smhow(in 1.17 version)...

**Comment by Slomaxonical-907** [comment]
will be fixed in the next release for 1.17.1.

**Comment by itsdinkd** [comment]
Next version?

**Comment by Heamaci** [comment]
You can use ferrite core, it has similar performance to hydrogen and it won't crash with this mod.

**Comment by red2blue** [comment]
I actually use both hydrogen and ferritecore. is that redundant to do?

**Comment by itsdinkd** [comment]
For results you should use both FerriteCore and Hydrogen says FC Dev, (which i already do).

Cannot take out a mod out of my optimization stack for this. He already made it compatible though, check the commits https://github.com/Slomaxonical-907/Architects-Palette-Fabric/commit/691bf58f3db39475a961974d525ee90ae87b5016. 
Not sure why he hasn't publicly released the updated version. 

I'm just going to compile the latest commit.
