### ISSUE TITLE
Crashing just after joining world

### ISSUE THREAD

**Issue by Fnige** [Slomaxonical-907/Architects-Palette-Fabric#20]
It seems that #16 still happens on 1.19

Quilt 0.17.1-beta.3 + qFAPI 2.0.0-alpha.4_0.56.1

Crash log
https://gist.github.com/FnigePython/7648f1d6c1c1b862c874116d04fecbff

**Comment by Slomaxonical-907** [comment]
oh no i forgot to port the fiix from 1.18 XD

**Comment by Slomaxonical-907** [comment]
released 2.2.1

**Comment by Slomaxonical-907** [comment]
Ok please confirm if it is fixed. Because some1 on the quilt team just said that it is probably a qfapi issue. @FnigePython
