### ISSUE TITLE
Add 1.19.2 compatibility to Modrinth

### ISSUE THREAD

**Issue by obvionaoe** [Slomaxonical-907/Architects-Palette-Fabric#29]
Hey, I take it this mod supports 1.19.2, but in Modrinth only 1.19 is stated as supported, so packwiz (a tool I'm using to create a modpack) cannot install it in a 1.19.2 modpack.

Could you please add it to Modrinth?

Thank you

**Comment by Slomaxonical-907** [comment]
sure
