### ISSUE TITLE
[BUG] Warpstone Creation Process Fails In Starry Skies Dimensions

### ISSUE THREAD

**Issue by ghost** [Slomaxonical-907/Architects-Palette-Fabric#3]
I've left an issue with the Starry Skies dev [here](https://github.com/DaFuqs/StarrySky/issues/29), however, I figure it's appropriate to also create an issue here, as I am not sure in which mod the fix can best be applied.

Starry Skies basically has an option to override the destination of the nether portal (and end portal) from the vanilla dimensions to Starry Skies equivalents. Depending on how that is done, or how this mod knows that a clay block has been sent through a nether portal, the issue (and corresponding fix) may lie either with this mod or that one.

I can confirm that the creation process functions as normal in the vanilla dimensions.

**Comment by Slomaxonical-907** [comment]
dunno why i left this for so long, the item needs to arrive at nether for the transformation to happen. I guess if there is another portal that leads to nether u should maybe try that. You could also try changing AP's recipe jsons to use the other dimentions.
