### ISSUE TITLE
[1.19.2] Works in versions 1.19.X

### ISSUE THREAD

**Issue by kingkuys2123** [Slomaxonical-907/Architects-Palette-Fabric#31]
This mod runs and works fine in 1.19.2 and the gameplay is smooth since installation, 
maybe edit and add 1.19.1 and 1.19.2 (and maybe 1.19.3) as supported/compatible versions in the CurseForge,
so it could be added to modpacks? Much love! :)

Since in the files it supports latest versions (>=) of all required dependencies.

**Comment by kingkuys2123** [comment]
bump

**Comment by BeeFox-sys** [comment]
has it been successfully tested with 1.19.3?
