### ISSUE TITLE
Hazard Block Side UV is broken

### ISSUE THREAD

**Issue by wontactcivilized** [Slomaxonical-907/Architects-Palette-Fabric#35]
North and West UV for Hazard Block is broken
![image](https://github.com/Slomaxonical-907/Architects-Palette-Fabric/assets/106423970/77d40d5b-01a6-46ed-85f3-33c79fba70d5)
Only happens for block
Slab and wall aren't affected

**Comment by BowBoy1** [comment]
Having the same issue with Unobtanium
