### ISSUE TITLE
Wither Bone is gone [1.18.1 Fabric]

### ISSUE THREAD

**Issue by itsdinkd** [Slomaxonical-907/Architects-Palette-Fabric#5]
For some reason, Witherbone is completely gone and replaced with Architect Palette's WIthered Bone. So when you kill withers they only drop AP withered bone. Vanilla one is completely erased. doesnt show in REI either. 

Using latest Architect Palette version
Loader 0.12.12 (happened on all loaders since 1.18+, did not happen on 1.17.1)

**Comment by Slomaxonical-907** [comment]
i've played on 1.18+ servers with this mod on and this is not the case

**Comment by itsdinkd** [comment]
> i've played on 1.18+ servers with this mod on and this is not the case

then your mod is conflicting with another mod but I guess that's not important, right?

**Comment by itsdinkd** [comment]
I use the version that you released on curseforge months ago. so not sure if you're playing on servers that use the latest commit or not, but Its in my modpack and you cannot just add commits as curseforge will deny it.

**Comment by Slomaxonical-907** [comment]
the servers were using the curseforge version. Im not sure what u mean that the vanilla bone doesnt show in REI, maybe u mean RER? If that is the case i'd love to see what is causing that since it's what I originally intended but then opted to inject into the existing loottable
